version: '3'
services:
  web:
    image: node:8.9.4
    ports:
      - 8080:8080
    command: bash -c "npm install && npm run dev"
    working_dir: /src
    volumes:
      - ".:/src"
    environment:
      HOST: 0.0.0.0
